package finanfx.frm;

import finanfx.dao.Cuentas;
import finanfx.models.Cuenta;
import finanfx.models.User;
import finanfx.state.LoggedInUser;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ander
 */
public class frmCuentas extends javax.swing.JPanel {

    Cuentas accountService = new Cuentas();

    /**
     * Creates new form frmCuentas
     */
    public frmCuentas() {
        initComponents();
        loadData();
    }

    public final void loadData() {
        try {
            User loggedUser = LoggedInUser.getInstance().getUser();
            int idUsuario = loggedUser.getID();
            ArrayList<Cuenta> cuentas = accountService.getAccounntsByUserId(idUsuario);

            DefaultTableModel model = (DefaultTableModel) jTable_Accounts.getModel();
            model.setRowCount(0); // Clear existing data

            for (Cuenta cuenta : cuentas) {
                Object[] row = {
                    cuenta.getIdCuenta(),
                    cuenta.getTipoCuenta(),
                    cuenta.getNumeroCuenta(),
                    cuenta.getNombreBanco(),
                    cuenta.getSaldoInicial()
                };
                model.addRow(row); // Add new row to the table
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateAccount() {
        User loggedUser = LoggedInUser.getInstance().getUser();
        int idUsuario = loggedUser.getID();

        String id = txtId.getText();
        int idCuenta = (id != null && id.matches("\\d+")) ? Integer.parseInt(id) : 0;

        Double saldo = Double.valueOf(txtSaldo.getText());
        String command = SaveOrCreate.getText();

        Cuenta cuenta;
        cuenta = new Cuenta(
                idCuenta,
                idUsuario,
                (String) txtTipo.getSelectedItem(),
                txtCuenta.getText(),
                (String) cboBanco.getSelectedItem(),
                saldo
        );
        try {
            if (command.equals("Actualizar")) {
                accountService.updateCuenta(cuenta, idCuenta);
                JOptionPane.showMessageDialog(this, "Cuenta actualizada con éxito");
            } else {
                accountService.createCuenta(cuenta, idUsuario);
                JOptionPane.showMessageDialog(this, "Cuenta guardada con éxito");
            }
            loadData();
            clearTextBox();
        } catch (SQLException ex) {
            Logger.getLogger(frmCuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void validateDoubleInput(KeyEvent evt) {
        // Get the character entered
        char c = evt.getKeyChar();

        // Allow backspace, decimal point, and digits (0-9)
        if (Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == '.') {
            // Allow the character to be entered
            return;
        } else {
            // Consume the event to prevent invalid character input
            evt.consume();
        }
    }

    private void clearTextBox() {
        txtId.setText(null);
        txtCuenta.setText(null);
        txtSaldo.setText(null);
        txtTipo.setSelectedIndex(0);
        cboBanco.setSelectedIndex(0);
        SaveOrCreate.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCuenta = new javax.swing.JTextField();
        SaveOrCreate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboBanco = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Accounts = new javax.swing.JTable();
        txtTipo = new javax.swing.JComboBox<>();
        txtSaldo = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 204));

        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        SaveOrCreate.setText("Guardar");
        SaveOrCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveOrCreateMouseClicked(evt);
            }
        });
        SaveOrCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveOrCreateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Cuentas");
        jLabel5.setPreferredSize(new java.awt.Dimension(148, 32));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("No de Cuenta");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Banco");

        jLabel4.setText("Saldo Inicial");

        cboBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de America Central", "Banco Agrícola", "Banco Cuscatlan", "Banco Hipotecario", "Banco Promerica", "Banco Azul" }));
        cboBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBancoActionPerformed(evt);
            }
        });

        jButton4.setText("Editar");

        jLabel1.setText("Tipo de cuenta");

        jButton5.setText("Eliminar");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Cuenta");

        jTable_Accounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Numero", "Banco", "Saldo Inicial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_AccountsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Accounts);
        if (jTable_Accounts.getColumnModel().getColumnCount() > 0) {
            jTable_Accounts.getColumnModel().getColumn(0).setResizable(false);
            jTable_Accounts.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_Accounts.getColumnModel().getColumn(1).setResizable(false);
            jTable_Accounts.getColumnModel().getColumn(2).setResizable(false);
            jTable_Accounts.getColumnModel().getColumn(3).setResizable(false);
            jTable_Accounts.getColumnModel().getColumn(4).setResizable(false);
        }

        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros", "Corriente", "Tarjeta de Crédito" }));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaldoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboBanco, 0, 206, Short.MAX_VALUE)
                                            .addComponent(txtCuenta)
                                            .addComponent(txtTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldo))
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SaveOrCreate)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)))
                                .addGap(72, 72, 72)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboBanco, txtCuenta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveOrCreate)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboBanco, txtCuenta, txtId});

    }// </editor-fold>//GEN-END:initComponents

    private void SaveOrCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveOrCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveOrCreateActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cboBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBancoActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void jTable_AccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_AccountsMouseClicked
        int index = jTable_Accounts.getSelectedRow();
        TableModel model = jTable_Accounts.getModel();

        txtId.setText(model.getValueAt(index, 0).toString());
        txtTipo.setSelectedItem(model.getValueAt(index, 1).toString());
        txtCuenta.setText(model.getValueAt(index, 2).toString());
        cboBanco.setSelectedItem(model.getValueAt(index, 3).toString());
        txtSaldo.setText(model.getValueAt(index, 4).toString());
        SaveOrCreate.setText("Actualizar");
    }//GEN-LAST:event_jTable_AccountsMouseClicked

    private void SaveOrCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveOrCreateMouseClicked
        updateAccount();
    }//GEN-LAST:event_SaveOrCreateMouseClicked

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void txtSaldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyPressed

    }//GEN-LAST:event_txtSaldoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveOrCreate;
    private javax.swing.JComboBox<String> cboBanco;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Accounts;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables
}
