package finanfx.frm;

/**
 * @author Ander
 */
import javax.swing.JOptionPane;
import finanfx.dao.Login;

public class frmLogin extends javax.swing.JFrame {

    Login loginService = new Login();

    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static int Miembro = 0;

    public void login() {
        try {
            if (loginService.validateUserLogin(txtUsuario.getText(), txtClave.getText()) > 0) {
                Miembro = loginService.validateUserLogin(txtUsuario.getText(), txtClave.getText());
                frmMenu menu = new frmMenu();
                menu.setVisible(true);
                this.hide();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }

        } catch (Exception x) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }
    }

    public void changePassword() {
        this.hide();
        frmClave contra = new frmClave();
        contra.setVisible(true);
    }

    public void singup() {
        this.hide();
        frmRegistroUsuario singup = new frmRegistroUsuario();
        singup.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        lblCambiarClave = new javax.swing.JLabel();
        lblRegistrarCuenta = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 130, 32);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(140, 80, 198, 25);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 80, 50, 25);

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtClave);
        txtClave.setBounds(140, 120, 198, 25);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 70, 25);

        lblCambiarClave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambiarClave.setText("Cambiar contraseña");
        lblCambiarClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarClaveMouseClicked(evt);
            }
        });
        getContentPane().add(lblCambiarClave);
        lblCambiarClave.setBounds(50, 210, 150, 30);

        lblRegistrarCuenta.setText("¿No tienes una cuenta?");
        lblRegistrarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegistrarCuenta);
        lblRegistrarCuenta.setBounds(220, 210, 140, 30);

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceder);
        btnAcceder.setBounds(240, 160, 95, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        login();
    }//GEN-LAST:event_btnAccederActionPerformed

    private void lblCambiarClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarClaveMouseClicked
        changePassword();
    }//GEN-LAST:event_lblCambiarClaveMouseClicked

    private void lblRegistrarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarCuentaMouseClicked
        singup();
    }//GEN-LAST:event_lblRegistrarCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCambiarClave;
    private javax.swing.JLabel lblRegistrarCuenta;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
