package finanfx.frm;

import finanfx.models.User;
import finanfx.state.LoggedInUser;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ander
 */
public class frmMenu extends javax.swing.JFrame {

    User loggedUser = LoggedInUser.getInstance().getUser();

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);

        String nombreCompleto = "Bienvenido " + loggedUser.getNombre() + " " + loggedUser.getApellido();
        lblWelcome.setText(nombreCompleto);
    }

    public void Apagado() throws SQLException {
        frmCuentas cuenta = new frmCuentas();
        cuenta.setVisible(false);
        frmPerfil perfil = new frmPerfil();
        perfil.setVisible(false);
        frmPresupuestos presupuesto = new frmPresupuestos();
        presupuesto.setVisible(false);
        frmTransacciones Transacciones = new frmTransacciones();
        Transacciones.setVisible(false);
        frmNotas note = new frmNotas();
        note.setVisible(false);
        content.removeAll();
        frmLogin Logueo = new frmLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        menuCuentasBancarias = new javax.swing.JMenuItem();
        menuPresupuestos = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenuItem();
        menuPerfil = new javax.swing.JMenuItem();
        menuTransacciones = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuPrep2 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 600));
        getContentPane().setLayout(null);

        lblWelcome.setText("Bienvenido (Nombre de usuario)");
        getContentPane().add(lblWelcome);
        lblWelcome.setBounds(20, 510, 250, 16);

        content.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(content);
        content.setBounds(0, 0, 560, 570);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(650, 32768));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(560, 23));

        jMenu5.setText("Mi Cuenta");

        menuCuentasBancarias.setText("Cuentas de banco");
        menuCuentasBancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentasBancariasActionPerformed(evt);
            }
        });
        jMenu5.add(menuCuentasBancarias);

        menuPresupuestos.setText("Mis Presupuestos");
        menuPresupuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPresupuestosActionPerformed(evt);
            }
        });
        jMenu5.add(menuPresupuestos);

        menuNotas.setText("Notas");
        menuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotasActionPerformed(evt);
            }
        });
        jMenu5.add(menuNotas);

        menuPerfil.setText("Ajustes del perfil");
        menuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerfilActionPerformed(evt);
            }
        });
        jMenu5.add(menuPerfil);

        menuTransacciones.setText("Transacciones");
        menuTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaccionesActionPerformed(evt);
            }
        });
        jMenu5.add(menuTransacciones);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ingresos y gastos");

        menuPrep2.setText("Presupuesto");
        menuPrep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrep2ActionPerformed(evt);
            }
        });
        jMenu6.add(menuPrep2);

        jMenuBar1.add(jMenu6);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaccionesActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        frmTransacciones Transaccion = null;

        try {
            Transaccion = new frmTransacciones();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        content.add(Transaccion);
        Dimension tCont = content.getSize();
        Dimension tiFrame = Transaccion.getSize();

        Transaccion.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        Transaccion.setVisible(true);
    }//GEN-LAST:event_menuTransaccionesActionPerformed

    private void menuCuentasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentasBancariasActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmCuentas Banco = new frmCuentas();
        content.add(Banco);
        Dimension tCont = content.getSize();
        Dimension tiFrame = Banco.getSize();
        Banco.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        Banco.setVisible(true);
    }//GEN-LAST:event_menuCuentasBancariasActionPerformed

    private void menuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotasActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmNotas note = new frmNotas();
        content.add(note);
        Dimension tCont = content.getSize();
        Dimension tiFrame = note.getSize();
        note.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        note.setVisible(true);
    }//GEN-LAST:event_menuNotasActionPerformed

    private void menuPresupuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPresupuestosActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmPresupuestos Presupuestos = new frmPresupuestos();
        content.add(Presupuestos);
        Dimension tCont = content.getSize();
        Dimension tiFrame = Presupuestos.getSize();
        Presupuestos.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        Presupuestos.setVisible(true);
    }//GEN-LAST:event_menuPresupuestosActionPerformed

    private void menuPrep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrep2ActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmPresupuestos Presupuestos = new frmPresupuestos();
        content.add(Presupuestos);
        Dimension tCont = content.getSize();
        Dimension tiFrame = Presupuestos.getSize();
        Presupuestos.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        Presupuestos.setVisible(true);
    }//GEN-LAST:event_menuPrep2ActionPerformed

    private void menuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerfilActionPerformed
        try {
            Apagado();
        } catch (SQLException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        frmPerfil Info = new frmPerfil();
        content.add(Info);
        Dimension tCont = content.getSize();
        Dimension tiFrame = Info.getSize();
        Info.setLocation((tCont.width - tiFrame.width) / 2, (tCont.height - tiFrame.height) / 2);
        content.revalidate();
        Info.setVisible(true);
    }//GEN-LAST:event_menuPerfilActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        int confirm;
        confirm = JOptionPane.showConfirmDialog(null,
                "¿Estas seguro que deseas salir?", "Confirmar salir",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    private String UserName;

    public frmMenu(String Username) {
        initComponents();
        this.UserName = Username;
        lblWelcome.setText("Bienvenido, " + Username + " !");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem menuCuentasBancarias;
    private javax.swing.JMenuItem menuNotas;
    private javax.swing.JMenuItem menuPerfil;
    private javax.swing.JMenuItem menuPrep2;
    private javax.swing.JMenuItem menuPresupuestos;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuTransacciones;
    // End of variables declaration//GEN-END:variables
}
