package finanfx.frm;

/*
 * @author Ander
 */
import finanfx.dao.Notas;
import javax.swing.JOptionPane;
import finanfx.models.Nota;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class frmNotas extends javax.swing.JPanel {

    private final int transactionId;

    /**
     * Creates new form frmNotas
     *
     * @param transactionId
     */
    public frmNotas(int transactionId) {
        this.transactionId = transactionId;
        initComponents();
        clearData();
        loadData();
    }

    public final void loadData() {
        try {
            ArrayList<Nota> notes = Notas.searchNotes(transactionId);

            DefaultTableModel model = (DefaultTableModel) jTable_Notes.getModel();
            model.setRowCount(0);

            for (Nota note : notes) {
                Object[] row = {
                    note.getID_Nota(),
                    note.getNota(),};
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPresupuestos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearData() {
        txtNota.setText("");
        txtIDNota.setText("");
        btnDelete.setEnabled(false);
        btnSaveoOrUpdate.setText("Guardar");
    }

    public void loadTableToForm() {
        int index = jTable_Notes.getSelectedRow();
        TableModel model = jTable_Notes.getModel();

        txtIDNota.setText(model.getValueAt(index, 0).toString());
        txtNota.setText(model.getValueAt(index, 1).toString());

        btnSaveoOrUpdate.setText("Actualizar");
        btnDelete.setEnabled(true);
    }

    public void saveNote() {
        try {
            String GNotas = txtNota.getText();
            if (GNotas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe incluir un texto en la nota");
                return;
            }
            Nota note = new Nota(
                    transactionId,
                    GNotas
            );
            String idNote = txtIDNota.getText();

            if (idNote.isEmpty()) {
                Notas.saveNotas(note);
                JOptionPane.showMessageDialog(this, "Nota guardada exitosamente.");
            } else {
                note.setID_Nota(Integer.parseInt(idNote));
                Notas.updateNota(note);
                JOptionPane.showMessageDialog(this, "Nota actualizada exitosamente.");
            }
            loadData();

            clearData();
        } catch (Exception x) {
            JOptionPane.showMessageDialog(this, "Error al guardar la Nota: " + x.getMessage());
        }
    }

    public void removeNote() {
        try {
            int idnota = Integer.parseInt(txtIDNota.getText());

            Notas.deleteNota(idnota);
            JOptionPane.showMessageDialog(this, "Nota Eliminada exitosamente.");
            clearData();
            loadData();

        } catch (Exception x) {
            JOptionPane.showMessageDialog(this, "Error Eliminando nota.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSaveoOrUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        btnClean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Notes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        txtIDNota.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Notas");
        jLabel1.setPreferredSize(new java.awt.Dimension(148, 32));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nota");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID nota");

        btnSaveoOrUpdate.setText("Guardar");
        btnSaveoOrUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveoOrUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtNota.setColumns(20);
        txtNota.setRows(5);
        txtNota.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtNota);
        txtNota.getAccessibleContext().setAccessibleName("");

        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jTable_Notes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Notes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NotesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Notes);
        if (jTable_Notes.getColumnModel().getColumnCount() > 0) {
            jTable_Notes.getColumnModel().getColumn(0).setMinWidth(30);
            jTable_Notes.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Notes.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable_Notes.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSaveoOrUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnClean))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIDNota, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDNota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSaveoOrUpdate)
                    .addComponent(btnClean))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        txtIDNota.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveoOrUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveoOrUpdateActionPerformed
        saveNote();
    }//GEN-LAST:event_btnSaveoOrUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        removeNote();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        clearData();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jTable_NotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NotesMouseClicked
        loadTableToForm();
    }//GEN-LAST:event_jTable_NotesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSaveoOrUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Notes;
    private javax.swing.JTextField txtIDNota;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
